<%@ Page Title="Test" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Test.aspx.cs" Inherits="MIS5370_18SP.Test" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>This is a test page:</h3>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:mis5370ConnectionString %>" SelectCommand="SELECT * FROM [Inventory]" DeleteCommand="DELETE FROM [Inventory] WHERE [Inventory_Tag_ID] = @Inventory_Tag_ID" InsertCommand="INSERT INTO [Inventory] ([Inventory_Tag_ID], [Room_Number], [Inventory_Quantity], [Inventory_Status], [Recommended_Amt], [Urgency_Indicator]) VALUES (@Inventory_Tag_ID, @Room_Number, @Inventory_Quantity, @Inventory_Status, @Recommended_Amt, @Urgency_Indicator)" UpdateCommand="UPDATE [Inventory] SET [Room_Number] = @Room_Number, [Inventory_Quantity] = @Inventory_Quantity, [Inventory_Status] = @Inventory_Status, [Recommended_Amt] = @Recommended_Amt, [Urgency_Indicator] = @Urgency_Indicator WHERE [Inventory_Tag_ID] = @Inventory_Tag_ID" OnSelecting="SqlDataSource1_Selecting">
        <DeleteParameters>
            <asp:Parameter Name="Inventory_Tag_ID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Inventory_Tag_ID" Type="Int32" />
            <asp:Parameter Name="Room_Number" Type="Int32" />
            <asp:Parameter Name="Inventory_Quantity" Type="Int32" />
            <asp:Parameter Name="Inventory_Status" Type="String" />
            <asp:Parameter Name="Recommended_Amt" Type="Int32" />
            <asp:Parameter Name="Urgency_Indicator" Type="Boolean" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Room_Number" Type="Int32" />
            <asp:Parameter Name="Inventory_Quantity" Type="Int32" />
            <asp:Parameter Name="Inventory_Status" Type="String" />
            <asp:Parameter Name="Recommended_Amt" Type="Int32" />
            <asp:Parameter Name="Urgency_Indicator" Type="Boolean" />
            <asp:Parameter Name="Inventory_Tag_ID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Inventory_Tag_ID" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" Height="50px" Width="125px">
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <Fields>
            <asp:BoundField DataField="Inventory_Tag_ID" HeaderText="Inventory_Tag_ID" ReadOnly="True" SortExpression="Inventory_Tag_ID" />
            <asp:BoundField DataField="Room_Number" HeaderText="Room_Number" SortExpression="Room_Number" />
            <asp:BoundField DataField="Inventory_Quantity" HeaderText="Inventory_Quantity" SortExpression="Inventory_Quantity" />
            <asp:BoundField DataField="Inventory_Status" HeaderText="Inventory_Status" SortExpression="Inventory_Status" />
            <asp:BoundField DataField="Recommended_Amt" HeaderText="Recommended_Amt" SortExpression="Recommended_Amt" />
            <asp:CheckBoxField DataField="Urgency_Indicator" HeaderText="Urgency_Indicator" SortExpression="Urgency_Indicator" />
        </Fields>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
    </asp:DetailsView>
</asp:Content>
